slug: sample-multiple-choice
title: Sample Multiple Choice Question
language: none
type: multiple-choice
difficulty: easy
tags: [concept, quiz]
entry: answer.md
test:
  kind: none
  file: none
timeout_ms: 0

# Multiple choice configuration
multipleChoice:
  question: "Which of the following are valid Python data types?"
  allowMultiple: true
  options:
    - id: "a"
      text: "list"
      correct: true
    - id: "b" 
      text: "dictionary"
      correct: true
    - id: "c"
      text: "array"
      correct: false
    - id: "d"
      text: "tuple"
      correct: true
  correctAnswers: ["a", "b", "d"]
  explanation: "Python has built-in list, dictionary, and tuple types. Arrays are available through the array module or NumPy, but are not built-in types."